
export const UserActionTypes = {
    /**
     * LOGIN ACTION TYPES
     */
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
  
    /**
     * SIGNUP ACTION TYPES
     */
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",

    /**
     * GET USER ACTION TYPES
     */
     USER_FETCH_START:"USER_FETCH_START",
     USER_FETCH_SUCCESS:"USER_FETCH_SUCCESS",
     USER_FETCH_FAILURE:"USER_FETCH_FAILURE",

    /**
     * SEARCH ACTION TYPES
     */
     USERS_SEARCH_START: "USERS_SEARCH_START",
     USERS_SEARCH_SUCCESS_: "USERS_SEARCH_SUCCESS_",
     USERS_SEARCH_ERROR: "USERS_SEARCH_ERROR",

    
    
    /**
     * LOGOUT ACTION TYPES
     */
    LOG_OUT: "LOG_OUT",
  };
  
