export const MessageActionTypes = {

    /**
     * GET MESSAGE ACTION TYPES
     */

     MESSAGE_FETCH_START:"MESSAGE_FETCH_START",
     MESSAGE_FETCH_SUCCESS:"MESSAGE_FETCH_SUCCESS",
     MESSAGE_FETCH_FAILURE:"MESSAGE_FETCH_FAILURE",


    /**
     * CREATE MESSAGE ACTION TYPES
     */

       MESSAGE_CREATE_START:"MESSAGE_CREATE_START",
       MESSAGE_CREATE_SUCCESS:"MESSAGE_CREATE_SUCCESS",
       MESSAGE_CREATE_FAILURE:"MESSAGE_CREATE_FAILURE",


    /**
     * UPDATE MESSAGE ACTION TYPES
     */

        MESSAGE_UPDATE_START:"MESSAGE_UPDATE_START",
        MESSAGE_UPDATE_SUCCESS:"MESSAGE_UPDATE_SUCCESS",
        MESSAGE_UPDATE_FAILURE:"MESSAGE_UPDATE_FAILURE",

    /**
     * DELETE MESSAGE ACTION TYPES
     */

         MESSAGE_DELETE_START:"MESSAGE_DELETE_START",
         MESSAGE_DELETE_SUCCESS:"MESSAGE_DELETE_SUCCESS",
         MESSAGE_DELETE_FAILURE:"DELETE_MESSAGE_FAILURE",
  


       
};